export const dummyProducts = [
  {
    id: 1,
    name: "Far cry 6",
    price: 50.49,
    photo: "/image/1.jpeg",
    address:"./farcry",
  },
  {
    id: 2,
    name: "HUMANKIND",
    price: 60,
    photo: "/image/2.jpeg",
    address:"./humankind",
  },
  {
    id: 3,
    name: "FIFA 22",
    price: 49.79,
    photo: "/image/3.jpeg",
    address:"./fifa",
  },
  {
    id: 4,
    name: "Resident Evil Village",
    price: 25.36,
    photo: "/image/4.jpeg",
    address:"./resident",

  },
  {
    id: 5,
    name: "Mass Effect Legendary",
    price: 47.95,
    photo: "/image/5.jpeg",
    address:"./MassEffectLegendary",
  },
  {
    id: 6,
    name: "Assassin's Creed Valhalla",
    price: 29.57,
    photo: "/image/6.jpeg",
    address:"./assassinsCreedValhalla",
  },
  {
    id: 7,
    name: "Anthem Origin",
    price: 12.98,
    photo: "/image/7.jpg",
    address:"./anthemOrigin",
  },
  {
    id: 8,
    name: "House of Ashes",
    price: 22.84,
    photo: "/image/8.jpeg",
    address:"./houseofAshes",
  },
  {
    id: 9,
    name: "Red Dead Redemption 2",
    price: 41.99,
    photo: "/image/9.jpeg",
    address:"./redDead",
  },
  {
    id: 10,
    name: "Days Gone",
    price: 24.69,
    photo: "/image/10.jpeg",
    address:"./daysGone",
  },
  {
    id: 11,
    name: "Monster Hunter: World",
    price: 23.99,
    photo: "/image/11.jpg",
    address:"./monsterHunterWorld",
  },
  {
    id: 12,
    name: "Monster Hunter Stories 2",
    price: 49,
    photo: "/image/12.jpeg",
    address:"./monsterHunterStoriesTwo",
  },{
    id: 13,
    name: "WRC 10",
    price: 21.95,
    photo: "/image/13.jpeg",
    address:"./wrcTen",
  },{
    id: 14,
    name: "GTA: San Andreas",
    price: 10,
    photo: "/image/14.jpg",
    address:"./gta",
  },
  {
    id: 15,
    name: "Call of Duty: Black Ops 3",
    price: 50.99,
    photo: "/image/15.jpg",
    address:"./callofDutyBlack",
  },{
    id: 16,
    name: "Watch Dogs Legion",
    price: 18.66,
    photo: "/image/16.jpeg",
    address:"./watchDogsLegion",
  },
];
